name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          # Create a build directory
          mkdir -p build
          
          # Copy all files from citation-chat directory
          cp -r citation-chat/* build/
          
          # Create a root index.html that redirects to the citation-chat
          cat > build/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta http-equiv="refresh" content="0; url=index.html">
              <title>Redirecting to Citation Chat</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      text-align: center;
                      padding: 40px;
                      line-height: 1.6;
                  }
                  .container {
                      max-width: 600px;
                      margin: 0 auto;
                  }
                  h1 {
                      color: #2196f3;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Citation Chat</h1>
                  <p>Redirecting to the Citation Chat application...</p>
                  <p>If you are not redirected automatically, <a href="index.html">click here</a>.</p>
              </div>
          </body>
          </html>
          EOF
          
          # List the contents of the build directory to verify
          echo "Contents of build directory:"
          ls -R build/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 